spring.application.name=SistemaPago
spring.datasource.url=jdbc:postgresql://localhost:5432/db_users
spring.datasource.username=admin
spring.datasource.password=Admin1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true